### ISSUE TITLE
pp

### ISSUE THREAD

**Issue by dotztv** [1440-2b2t/Pyro-Client#10]
i have tried putting it in the versions folder and it didnt work(maybe because it doesnt have a .json file), i tried the jar itself and nothing happend

**Comment by d524342423** [comment]
> i have tried putting it in the versions folder and it didnt work(maybe because it doesnt have a .json file), i tried the jar itself and nothing happend

Your supposed to place in mod folder

**Comment by pwn3r1** [comment]
you don't.
