### ISSUE TITLE
Not sure if i'm willing to trust it

### ISSUE THREAD

**Issue by MIshaTheWarlord** [1440-2b2t/Pyro-Client#2]
A cracked version of a client, when a different cracked version has previously been backdoored? idk about that

**Comment by svxl** [comment]
Its Backdoored

**Comment by Crystallinqq** [comment]
theres not a different version thats backdoored stfu

**Comment by 1440-2b2t** [comment]
> theres not a different version thats backdoored stfu

Agreed!
