### ISSUE TITLE
This is the same client crack that crystalinqq backdoored 

### ISSUE THREAD

**Issue by MIshaTheWarlord** [1440-2b2t/Pyro-Client#3]
This is almost certainly backdoored, it is the same file, just with an edited file name, as the backdoored crack that crystalinqq put out.

**Comment by svxl** [comment]
Its BackDoored

**Comment by FerrumTheElement** [comment]
have any code to prove it? and its not the same as crystallinqq's because this has auto dupe and crystallinqq's doesnt

**Comment by MIshaTheWarlord** [comment]
I sadly have no code to prove it. If you are willing to trust a public leak that's your decision and I wish you luck in it not being backdoored. The fact that it was previously named "Crysalinqq's Pyro crack 1.4.1" (or something along those lines, I'm not one hundred percent sure) was rather off-putting to me.

**Comment by MIshaTheWarlord** [comment]
(And no, I didn't actually know about the fact that Crystalinqq's crack did not have autodupe)

**Comment by FerrumTheElement** [comment]
how could you say that something is a backdoor when you obviously have no evidence????

**Comment by Hiiva** [comment]
The file is identical to the one posted by crystallinqq.

**Comment by ghost** [comment]
How about you leak the source code and we will find out for ourselves instead of yall squabbling like little kids

**Comment by Thousandstar-dev** [comment]
you can decompile the src via http://www.decompiler.com/ then you can look through the shit and see all the code. Maybe there is a backdoor maybe there isnt. I doubt it would be to because on github if you dont say you backdoored code you can get into a lot of trouble.

**Comment by ghost** [comment]
if thats the case you shouldnt release the jar if you dont know what you are dealing with and if this is a backdoor then you could get "in trouble"

**Comment by Crystallinqq** [comment]
mine isn’t backdoored and none of you can prove it.

**Comment by ghost** [comment]
> mine isn’t backdoored and none of you can prove it.

monkeys stupid

**Comment by B2H990** [comment]
GUYS I FOUND THE BACKDOOR IT'S..... not backdoored

**Comment by ghost** [comment]
> mine isn’t backdoored and none of you can prove it.

and yet you dont provide the source code in spite of all the accusations you defended smh

**Comment by Crystallinqq** [comment]
> > mine isn’t backdoored and none of you can prove it.
> 
> and yet you dont provide the source code in spite of all the accusations you defended smh

You dont know how cracking works. You don’t just pull the source code out of nowhere. Please learn a bit about what your talking about b4 acting like you know what ur doing to someone who does.

**Comment by ghost** [comment]
> > mine isn’t backdoored and none of you can prove it.
> 
> and yet you dont provide the source code in spite of all the accusations you defended smh

🤡

**Comment by B2H990** [comment]
> > mine isn’t backdoored and none of you can prove it.
> 
> and yet you dont provide the source code in spite of all the accusations you defended smh

That's not how it works your legit monkey. He doesn't have sourcecode, He edited compiled binaries to make the crack.

**Comment by MIshaTheWarlord** [comment]
This is just an argument at this point, that's why I closed it.

**Comment by ghost** [comment]
> This is just an argument at this point, that's why I closed it.

good move considering youre completely retarded
