### ISSUE TITLE
Backdoored DONT DOWNLOAD

### ISSUE THREAD

**Issue by hxrry-999** [1440-2b2t/Pyro-Client#5]

**Comment by 1440-2b2t** [comment]
Its not backdoored

**Comment by notperry1** [comment]
oh really show us the highly obfuscated code where the backdoor is you cant read code if your life depended on it (also recommends inertia hahahaha)

**Comment by notperry1** [comment]
and woah inertia is highly obfuscated does that mean its also ratted!?!?!? your logic messed up my guy
